add test capa presubmit to test boskos integration
vagator/test-infra pull request #87
Opened 2022-03-07 09:03 UTC by Priyankasaggu11929

The PR adds a test CAPA presubmit job to test the Boskos integration.

Added components:
- Add presubmit on vagator/cluster-api-provider-aws `test-capa-presubmits`
- Update `plugins.yaml` to add `vagator/cluster-api-provider-aws` under the repos.
- Update `config.yaml` to add presets:
    - `preset-kind-volume-mounts: "true"`
    - `preset-service-account: "true"`
- Add test-grid dashboard:`sig-cluster-lifecycle-cluster-api-provider-aws`

2022-03-09 15:12 UTC, rajaskakodkar requested changes
Let's start with a TCE AWS job and then move to capa later

2022-03-09 15:12 UTC, rajaskakodkar commented on config/jobs/cluster-api-provider-aws/presubmits.yaml
> +        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220221-c13e827224-master
Lets test this with `public.ecr.aws/t0q8k6g2/vagator/test-image:v20220803-82253a6`

2022-03-09 15:12 UTC, rajaskakodkar commented on config/prow/config.yaml
> +  - name: GOOGLE_APPLICATION_CREDENTIALS
We won't require this.

2022-03-09 15:12 UTC, rajaskakodkar commented on config/prow/config.yaml
> +    preset-service-account: "true"
We won't require this.

2022-03-09 15:12 UTC, rajaskakodkar commented on config/prow/config.yaml
> +    preset-service-account: "true"
We won't require this.

2022-03-09 15:12 UTC, rajaskakodkar commented on config/prow/config.yaml
> +    preset-kind-volume-mounts: "true"
Thanks for adding this preset!

2022-03-09 15:12 UTC, rajaskakodkar commented on config/prow/config.yaml
> +    preset-kind-volume-mounts: "true"
Thanks for adding this preset!

2022-03-09 15:12 UTC, rajaskakodkar commented on config/jobs/cluster-api-provider-aws/presubmits.yaml
> +  - name: test-capa-presubmits
Let's start integrating Boskos with a TCE AWS job first.

2022-03-09 15:12 UTC, rajaskakodkar commented on config/jobs/cluster-api-provider-aws/presubmits.yaml
> +  - name: test-capa-presubmits
Let's start integrating Boskos with a TCE AWS job first.

2022-03-10 08:51 UTC, Priyankasaggu11929 commented
Hey thanks @rajaskakodkar for the review. I got busy in some other stuff & missed redoing it. I'm closing this one, will raise a fresh PR taking in all review comments from above.

2022-03-10 08:51 UTC, closed without merging